### ISSUE TITLE
Vagrantfil in README fails on OSX 10.7

### ISSUE THREAD

**Issue by EpocSquadron** [xironix/freebsd-vagrant#12]
First, ruby gives a syntax error in the vagrantfile itself:

![image](https://f.cloud.github.com/assets/414963/345698/67d32008-9e29-11e2-9df6-3c808ae29667.png)

Ruby version:

```
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin11.0]
```

Then, when running vagrant up anyway, I receive:

```
Bringing machine 'default' up with 'virtualbox' provider...
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:257:in `initialize': can't convert nil into String (TypeError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:257:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:257:in `block in validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:253:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:253:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/root.rb:61:in `block in validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/root.rb:57:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/root.rb:57:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:37:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:32:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by denji** [comment]
``` bash
$ vagrant -v
Vagrant version 1.1.5
```

---

V1 disable = http://docs-v1.vagrantup.com/v1/docs/nfs.html

V2 = http://docs.vagrantup.com/v2/synced-folders/nfs.html

``` ruby
config.vm.synced_folder ".", "/vagrant", :nfs => true, id: "vagrant-root"
```
